apiVersion: v1
kind: Pod
metadata:
  name: hello-go-allowed
  labels:
    bats: test
spec:
  containers:
  - name: hello-go
    image: ttl.sh/bb3c61f9-1cf2-4585-b1b7-c41bd497ac25:1h #replace with your image here 
    ports:
    - containerPort: 80
    securityContext:
      privileged: false
      capabilities:
        drop:
          - ALL
    imagePullPolicy: Always