apiVersion: v1
kind: Pod
metadata:
  name: nginx-allowed
  labels:
    bats: test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    securityContext:
      privileged: false