apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: psp-permissive
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-permissive
subjects:
- kind: ServiceAccount
  name: daemon-set-controller
  namespace: kube-system
- kind: ServiceAccount
  name: replicaset-controller
  namespace: kube-system
- kind: ServiceAccount
  name: job-controller
  namespace: kube-system
- kind: ServiceAccount
  name: coredns
  namespace: kube-system
- kind: ServiceAccount
  name: kindnet
  namespace: kube-system
- kind: ServiceAccount
  name: kube-proxy
  namespace: kube-system
- kind: ServiceAccount
  name: node-controller
  namespace: kube-system
- kind: ServiceAccount
  name: attachdetach-controller
  namespace: kube-system
- kind: ServiceAccount
  name: bootstrap-signer
  namespace: kube-system
- kind: ServiceAccount
  name: certificate-controller
  namespace: kube-system
- kind: ServiceAccount
  name: clusterrole-aggregation-controller
  namespace: kube-system
- kind: ServiceAccount
  name: cronjob-controller
  namespace: kube-system
- kind: ServiceAccount
  name: deployment-controller
  namespace: kube-system
- kind: ServiceAccount
  name: disruption-controller
  namespace: kube-system
- kind: ServiceAccount
  name: endpoint-controller
  namespace: kube-system
- kind: ServiceAccount
  name: endpointslice-controller
  namespace: kube-system
- kind: ServiceAccount
  name: endpointslicemirroring-controller
  namespace: kube-system
- kind: ServiceAccount
  name: ephemeral-volume-controller
  namespace: kube-system
- kind: ServiceAccount
  name: expand-controller
  namespace: kube-system
- kind: ServiceAccount
  name: generic-garbage-collector
  namespace: kube-system
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
- kind: ServiceAccount
  name: namespace-controller
  namespace: kube-system
- kind: ServiceAccount
  name: persistent-volume-binder
  namespace: kube-system
- kind: ServiceAccount
  name: pod-garbage-collector
  namespace: kube-system
- kind: ServiceAccount
  name: pv-protection-controller
  namespace: kube-system
- kind: ServiceAccount
  name: pvc-protection-controller
  namespace: kube-system
- kind: ServiceAccount
  name: replication-controller
  namespace: kube-system
- kind: ServiceAccount
  name: resourcequota-controller
  namespace: kube-system
- kind: ServiceAccount
  name: root-ca-cert-publisher
  namespace: kube-system
- kind: ServiceAccount
  name: service-account-controller
  namespace: kube-system
- kind: ServiceAccount
  name: service-controller
  namespace: kube-system
- kind: ServiceAccount
  name: statefulset-controller
  namespace: kube-system
- kind: ServiceAccount
  name: token-cleaner
  namespace: kube-system
- kind: ServiceAccount
  name: ttl-after-finished-controller
  namespace: kube-system
- kind: ServiceAccount
  name: ttl-controller 
  namespace: kube-system
